"""initial schema

Revision ID: d08d8c8a7c9f
Revises: 
Create Date: 2026-08-04 21:35:02.165762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd08d8c8a7c9f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_username', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('hired_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('employee', 'hr', 'admin')", name='ck_employees_role'),
    sa.CheckConstraint("status IN ('invited', 'active', 'archived')", name='ck_employees_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_company_id'), 'employees', ['company_id'], unique=False)
    op.create_index('ix_employees_company_id_status', 'employees', ['company_id', 'status'], unique=False)
    op.create_index(op.f('ix_employees_telegram_user_id'), 'employees', ['telegram_user_id'], unique=False)
    op.create_index('uq_employees_company_id_telegram_user_id', 'employees', ['company_id', 'telegram_user_id'], unique=True)
    op.create_table('onboarding_programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_programs_company_id'), 'onboarding_programs', ['company_id'], unique=False)
    op.create_index('ix_onboarding_programs_company_id_is_active', 'onboarding_programs', ['company_id', 'is_active'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'completed', 'cancelled')", name='ck_assignments_status'),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['onboarding_programs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_assigned_by_id'), 'assignments', ['assigned_by_id'], unique=False)
    op.create_index(op.f('ix_assignments_company_id'), 'assignments', ['company_id'], unique=False)
    op.create_index('ix_assignments_company_id_status', 'assignments', ['company_id', 'status'], unique=False)
    op.create_index(op.f('ix_assignments_employee_id'), 'assignments', ['employee_id'], unique=False)
    op.create_index('ix_assignments_employee_id_status', 'assignments', ['employee_id', 'status'], unique=False)
    op.create_index(op.f('ix_assignments_program_id'), 'assignments', ['program_id'], unique=False)
    op.create_index('uq_assignments_employee_program_active', 'assignments', ['employee_id', 'program_id'], unique=True, postgresql_where=sa.text("status IN ('pending', 'in_progress')"))
    op.create_table('steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('step_type', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("step_type IN ('content', 'task', 'quiz', 'ack')", name='ck_steps_step_type'),
    sa.CheckConstraint('position >= 0', name='ck_steps_position_non_negative'),
    sa.ForeignKeyConstraint(['program_id'], ['onboarding_programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'position', name='uq_steps_program_id_position')
    )
    op.create_index(op.f('ix_steps_program_id'), 'steps', ['program_id'], unique=False)
    op.create_table('ai_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=True),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'closed')", name='ck_ai_conversations_status'),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_conversations_assignment_id', 'ai_conversations', ['assignment_id'], unique=False, postgresql_where=sa.text('assignment_id IS NOT NULL'))
    op.create_index(op.f('ix_ai_conversations_company_id'), 'ai_conversations', ['company_id'], unique=False)
    op.create_index('ix_ai_conversations_company_id_created_at', 'ai_conversations', ['company_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_conversations_employee_id'), 'ai_conversations', ['employee_id'], unique=False)
    op.create_index('ix_ai_conversations_employee_id_status', 'ai_conversations', ['employee_id', 'status'], unique=False)
    op.create_index('ix_ai_conversations_telegram_chat_id_status', 'ai_conversations', ['telegram_chat_id', 'status'], unique=False)
    op.create_table('knowledge_articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=True),
    sa.Column('step_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_id'], ['onboarding_programs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_articles_company_id'), 'knowledge_articles', ['company_id'], unique=False)
    op.create_index('ix_knowledge_articles_company_id_is_published', 'knowledge_articles', ['company_id', 'is_published'], unique=False)
    op.create_index(op.f('ix_knowledge_articles_created_by_id'), 'knowledge_articles', ['created_by_id'], unique=False)
    op.create_index('ix_knowledge_articles_program_id', 'knowledge_articles', ['program_id'], unique=False, postgresql_where=sa.text('program_id IS NOT NULL'))
    op.create_index('ix_knowledge_articles_step_id', 'knowledge_articles', ['step_id'], unique=False, postgresql_where=sa.text('step_id IS NOT NULL'))
    op.create_index('ix_knowledge_articles_tags', 'knowledge_articles', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('not_started', 'in_progress', 'completed', 'skipped')", name='ck_progress_status'),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'step_id', name='uq_progress_assignment_id_step_id')
    )
    op.create_index(op.f('ix_progress_assignment_id'), 'progress', ['assignment_id'], unique=False)
    op.create_index('ix_progress_assignment_id_status', 'progress', ['assignment_id', 'status'], unique=False)
    op.create_index(op.f('ix_progress_step_id'), 'progress', ['step_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_progress_step_id'), table_name='progress')
    op.drop_index('ix_progress_assignment_id_status', table_name='progress')
    op.drop_index(op.f('ix_progress_assignment_id'), table_name='progress')
    op.drop_table('progress')
    op.drop_index('ix_knowledge_articles_tags', table_name='knowledge_articles', postgresql_using='gin')
    op.drop_index('ix_knowledge_articles_step_id', table_name='knowledge_articles', postgresql_where=sa.text('step_id IS NOT NULL'))
    op.drop_index('ix_knowledge_articles_program_id', table_name='knowledge_articles', postgresql_where=sa.text('program_id IS NOT NULL'))
    op.drop_index(op.f('ix_knowledge_articles_created_by_id'), table_name='knowledge_articles')
    op.drop_index('ix_knowledge_articles_company_id_is_published', table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_company_id'), table_name='knowledge_articles')
    op.drop_table('knowledge_articles')
    op.drop_index('ix_ai_conversations_telegram_chat_id_status', table_name='ai_conversations')
    op.drop_index('ix_ai_conversations_employee_id_status', table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_employee_id'), table_name='ai_conversations')
    op.drop_index('ix_ai_conversations_company_id_created_at', table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_company_id'), table_name='ai_conversations')
    op.drop_index('ix_ai_conversations_assignment_id', table_name='ai_conversations', postgresql_where=sa.text('assignment_id IS NOT NULL'))
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_steps_program_id'), table_name='steps')
    op.drop_table('steps')
    op.drop_index('uq_assignments_employee_program_active', table_name='assignments', postgresql_where=sa.text("status IN ('pending', 'in_progress')"))
    op.drop_index(op.f('ix_assignments_program_id'), table_name='assignments')
    op.drop_index('ix_assignments_employee_id_status', table_name='assignments')
    op.drop_index(op.f('ix_assignments_employee_id'), table_name='assignments')
    op.drop_index('ix_assignments_company_id_status', table_name='assignments')
    op.drop_index(op.f('ix_assignments_company_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_assigned_by_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index('ix_onboarding_programs_company_id_is_active', table_name='onboarding_programs')
    op.drop_index(op.f('ix_onboarding_programs_company_id'), table_name='onboarding_programs')
    op.drop_table('onboarding_programs')
    op.drop_index('uq_employees_company_id_telegram_user_id', table_name='employees')
    op.drop_index(op.f('ix_employees_telegram_user_id'), table_name='employees')
    op.drop_index('ix_employees_company_id_status', table_name='employees')
    op.drop_index(op.f('ix_employees_company_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
